name: Generate Flathub Deps
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4
        with:
          repository: binarynonsense/comic-book-reader

      - name: SETUP NODE
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          
      - name: INSTALL TOOLS & CREATE FILE
        run: |
          pipx install git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node
          flatpak-node-generator npm package-lock.json
          ls
          cat generated-sources.json
